version: "3"

services:
  gateway:
    image: ghcr.io/noted-eip/api-gateway:latest
    pull_policy: always
    ports:
      - 3000:3000
    environment:
      - API_GATEWAY_ENV=production
      - API_GATEWAY_PORT=3000
      - API_GATEWAY_ACCOUNTS_SERVICE_ADDR=accounts:3000

  accounts:
    image: ghcr.io/noted-eip/accounts-service:latest
    pull_policy: always
    ports:
      - 3001:3000
    environment:
      - ACCOUNTS_SERVICE_ENV=production
      - ACCOUNTS_SERVICE_PORT=3000
      - ACCOUNTS_SERVICE_MONGO_URI=mongodb://mongo:27017
      - ACCOUNTS_SERVICE_MONGO_DB_NAME=accounts-service

  mongo:
    image: mongo
    volumes:
      - mongo:/data/db

volumes:
  mongo:
