version: "3"

services:
  accounts:
    build: ./accounts-service

  notes:
    build: ./notes-service

  recommendations:
    build: ./recommendations-service

  gateway:
    build: ./api-gateway
    ports:
      - 3000:80

  mongo:
    image: mongo
    volumes:
      - mongo:/data/db

volumes:
  mongo:
